services:
  db:
    image: postgres:14
    container_name: wedding.db
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ./dbdata:/var/lib/postgresql/data