version: "3"

services:
  db:
    image: postgres:14
    container_name: weddingdb
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - /dbdata:/var/lib/postgresql/data
    networks:
      - bc30138server_bc30138-net

  weddingweb:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    expose:
      - "8000"
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - bc30138server_bc30138-net

networks:
  bc30138server_bc30138-net:
    external: true
