version: "3"

services:
  db:
    image: postgres:14-alpine
    container_name: weddingdb
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - env/.env.docker.local
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  weddingweb:
    container_name: weddingweb
    build:
      context: docker/local
      dockerfile: ./docker/web/Dockerfile
    expose:
      - "8000"
    ports:
      - 8000:8000
    env_file:
      - env/.env.docker.local
    restart: always
    depends_on:
      - db
