version: "3"

services:
  db:
    image: postgres:14-alpine
    container_name: weddingdb
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    networks:
      - bc30138-net

  weddingweb:
    container_name: weddingweb
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    expose:
      - "8000"
    ports:
      - 8000:8000
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    networks:
      - bc30138-net

networks:
  bc30138-net:
    external: true
