"""add forms

Revision ID: 06bb00d3910f
Revises: 8341b26853fc
Create Date: 2023-03-03 16:58:55.987098

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "06bb00d3910f"
down_revision = "8341b26853fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forms",
        sa.Column("id", sa.Integer(), nullable=False, comment="Идентификатор бланка"),
        sa.Column("group_id", sa.Integer(), nullable=False, comment="Идентификатор группы"),
        sa.Column("plus", sa.String(), nullable=True, comment="Имя плюс одного"),
        sa.Column("attend", sa.Boolean(), nullable=False, comment="Прийдут ли гости из группы?"),
        sa.Column("transfer", sa.Boolean(), nullable=False, comment="Потребуется трансфер до коттеджа?"),
        sa.Column("sleepover", sa.Boolean(), nullable=False, comment="Останутся с ночевой?"),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id"),
        comment="Таблица бланков вопросов",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("forms")
    # ### end Alembic commands ###
