"""initial

Revision ID: 31500d66026a
Revises: cf93cb9ae689
Create Date: 2023-02-03 13:18:55.069535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31500d66026a'
down_revision = 'cf93cb9ae689'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'groups',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('guests_user_id_fkey', 'guests', type_='foreignkey')
    op.drop_column('guests', 'user_id')
    op.drop_table('users')
    op.add_column('guests', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key('guests_group_id_fkey', 'guests', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('guests_group_id_fkey', 'guests', type_='foreignkey')
    op.drop_column('guests', 'group_id')
    op.drop_table('groups')
    op.create_table(
        'users',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.add_column('guests', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('guests_user_id_fkey', 'guests', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
