"""add comments to guest

Revision ID: 8341b26853fc
Revises: eb13307e6722
Create Date: 2023-02-28 17:54:45.015600

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8341b26853fc"
down_revision = "eb13307e6722"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "guests",
        "id",
        existing_type=sa.INTEGER(),
        comment="Идентификатор гостя",
        existing_nullable=False,
        autoincrement=True,
    )
    op.alter_column("guests", "first_name", existing_type=sa.VARCHAR(), comment="Имя гостя", existing_nullable=False)
    op.alter_column(
        "guests", "middle_name", existing_type=sa.VARCHAR(), comment="Отчество гостя", existing_nullable=True
    )
    op.alter_column("guests", "last_name", existing_type=sa.VARCHAR(), comment="Фамилия гостя", existing_nullable=False)
    op.alter_column("guests", "male", existing_type=sa.VARCHAR(), comment="Пол гостя", existing_nullable=False)
    op.create_table_comment("guests", "Таблица гостей", existing_comment=None, schema=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment("guests", existing_comment="Таблица гостей", schema=None)
    op.alter_column(
        "guests",
        "male",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Пол гостя",
        existing_nullable=False,
    )
    op.alter_column(
        "guests",
        "last_name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Фамилия гостя",
        existing_nullable=False,
    )
    op.alter_column(
        "guests",
        "middle_name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Отчество гостя",
        existing_nullable=True,
    )
    op.alter_column(
        "guests",
        "first_name",
        existing_type=sa.VARCHAR(),
        comment=None,
        existing_comment="Имя гостя",
        existing_nullable=False,
    )
    op.alter_column(
        "guests",
        "id",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Идентификатор гостя",
        existing_nullable=False,
        autoincrement=True,
    )
    # ### end Alembic commands ###
