"""guest male and not nullable first and last name

Revision ID: 853f5503c194
Revises: 9bd3a45d31c0
Create Date: 2023-02-08 18:44:18.583015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853f5503c194'
down_revision = '9bd3a45d31c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guests', sa.Column('male', sa.String(), nullable=True))
    op.execute("UPDATE guests SET male = 'male'")
    op.alter_column('guests', 'male', nullable=False)

    op.alter_column('guests', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('guests', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guests', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('guests', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('guests', 'male')
    # ### end Alembic commands ###
