"""group unique name

Revision ID: 9bd3a45d31c0
Revises: a232d81aea52
Create Date: 2023-02-04 16:14:12.430789

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "9bd3a45d31c0"
down_revision = "a232d81aea52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("groups_name_key", "groups", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("groups_name_key", "groups", type_="unique")
    # ### end Alembic commands ###
