"""group schema with two guests, finalize and sleep_place

Revision ID: a232d81aea52
Revises: 31500d66026a
Create Date: 2023-02-04 15:04:52.395178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a232d81aea52'
down_revision = '31500d66026a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('sleep_place', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('groups', sa.Column('finalize', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('groups', sa.Column('guest_1_id', sa.Integer(), nullable=True))
    op.add_column('groups', sa.Column('guest_2_id', sa.Integer(), nullable=True))
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'groups', 'guests', ['guest_2_id'], ['id'])
    op.create_foreign_key(None, 'groups', 'guests', ['guest_1_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('groups', 'guest_2_id')
    op.drop_column('groups', 'guest_1_id')
    op.drop_column('groups', 'finalize')
    op.drop_column('groups', 'sleep_place')
    # ### end Alembic commands ###
