"""remove unused fields from groups

Revision ID: bd28141af4e3
Revises: 853f5503c194
Create Date: 2023-02-10 13:19:50.308229

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "bd28141af4e3"
down_revision = "853f5503c194"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "finalize")
    op.drop_column("groups", "sleep_place")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("sleep_place", sa.BOOLEAN(), server_default=sa.text("true"), autoincrement=False, nullable=False),
    )
    op.add_column(
        "groups",
        sa.Column("finalize", sa.BOOLEAN(), server_default=sa.text("false"), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
