"""Коды ошибок при выполнении выборки из бд гостей."""

GUESTS_DB_ERROR = "GUEST_DB_ERROR"
GUESTS_CONSTRAINT_ERROR = "GUESTS_CONSTRAINT_ERROR"
GUESTS_MULTIPLE_ROWS_FOUND_ERROR = "GUESTS_MULTIPLE_ROWS_FOUND_ERROR"
