name: Checks

on:
  push:
    branches: ["*"]

  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Packages setup
        run: |
          pip install pre-commit
      - name: Python linter [pre-commit]
        run: |
          python -m pre-commit run --all-files
